@baseUrl = http://localhost:5046
### 1️⃣ Create User
POST {{baseUrl}}/api/users
Content-Type: application/json

{
  "firstName": "Guido",
  "lastName": "Lavespa",
  "email": "g.lavespa+{{ $randomInt 1000 9999 }}@example.com"
}

> {% client.global.set("userId", response.body.userId); %}
###  Saved userId = {{userId}}

### 2️⃣ Get User by ID
GET {{baseUrl}}/api/users/{{userId}}
